  
  export const GET_DATA = {
    REQUEST: "GET_DATA_REQUEST",
    SUCCESS: "GET_DATA_SUCCESS",
    FAILURE: "GET_DATA_FAILURE",
    
  };

    
  export const SEND_MESSAGE = {
    REQUEST: "SEND_MESSAGE_REQUEST",
    SUCCESS: "SEND_MESSAGE_SUCCESS",
    FAILURE: "SEND_MESSAGE_FAILURE",
    
  };
  