  
  export const GET_DATA = {
    REQUEST: "GET_DATA_REQUEST",
    SUCCESS: "GET_DATA_SUCCESS",
    FAILURE: "GET_DATA_FAILURE",
    
  };

    
  export const SEND_MESSAGE = {
    REQUEST: "SEND_MESSAGE_REQUEST",
    SUCCESS: "SEND_MESSAGE_SUCCESS",
    FAILURE: "SEND_MESSAGE_FAILURE",
    
  };
  
  export const LOGIN = {
    REQUEST: "LOGIN_REQUEST",
    SUCCESS: "LOGIN_SUCCESS",
    FAILURE: "LOGIN_FAILURE",
    
  };

  export const REGISTER = {
    REQUEST: "REGISTER_REQUEST",
    SUCCESS: "REGISTER_SUCCESS",
    FAILURE: "REGISTER_FAILURE",
    
  };
  
  export const LOGOUT ={
    SUCCESS: "LOGOUT_SUCCESS",
  }


  export const SEND_USER_FORM  = {
    SUCCESS : "SEND_USER_FORM_SUCCESS",
    REQUEST : "SEND_USER_FORM",
    FAILURE : "SEND_USER_FORM_FAILURE"
  }


  export const CLEAR = {
    SUCCESS : "CLEAR"
  }